export const emojiData = {
  "::happy::": "😀",
  "::sad::": "😥",
  "::smile::": "🤣",
  "::yawning_face::": "🥱",
  "::girl::": "👧🏻",
  "::sheep::": "🐑",
  "::smiley::": "😃",
  "::grinning::": "😀",
  "::rofl::": "🤣",
  "::wink::": "😉",
  "::grin::": "😁",
  "::innocent::": "😇",
  "::heart_eyes::": "😍",
  "::thumbsup::": "👍🏻",
};
